//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblDistributor> tblDistributors { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblExportDetail> tblExportDetails { get; set; }
        public DbSet<tblExportReceipt> tblExportReceipts { get; set; }
        public DbSet<tblImportDetail> tblImportDetails { get; set; }
        public DbSet<tblImportReceipt> tblImportReceipts { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblStoreBuy> tblStoreBuys { get; set; }
    }
}
