//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistributor
    {
        public tblDistributor()
        {
            this.tblImportReceipts = new HashSet<tblImportReceipt>();
        }
    
        public string DistributorID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<tblImportReceipt> tblImportReceipts { get; set; }
    }
}
