//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.tblExportReceipts = new HashSet<tblExportReceipt>();
            this.tblImportReceipts = new HashSet<tblImportReceipt>();
        }
    
        public string EmployeeID { get; set; }
        public string EName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<tblExportReceipt> tblExportReceipts { get; set; }
        public virtual ICollection<tblImportReceipt> tblImportReceipts { get; set; }
    }
}
