//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExportReceipt
    {
        public tblExportReceipt()
        {
            this.tblExportDetails = new HashSet<tblExportDetail>();
        }
    
        public string ExportReceiptID { get; set; }
        public string EmployeeID { get; set; }
        public string StoreID { get; set; }
        public double TotalPrice { get; set; }
        public System.DateTime Date { get; set; }
        public string DeliveryStatus { get; set; }
        public string PayMethod { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual ICollection<tblExportDetail> tblExportDetails { get; set; }
        public virtual tblStoreBuy tblStoreBuy { get; set; }
    }
}
