//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public tblProduct()
        {
            this.tblExportDetails = new HashSet<tblExportDetail>();
            this.tblImportDetails = new HashSet<tblImportDetail>();
        }
    
        public string ProductID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public double ImportPrice { get; set; }
        public double ExportPrice { get; set; }
        public int Quantity { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<tblExportDetail> tblExportDetails { get; set; }
        public virtual ICollection<tblImportDetail> tblImportDetails { get; set; }
    }
}
