//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreBuy
    {
        public tblStoreBuy()
        {
            this.tblExportReceipts = new HashSet<tblExportReceipt>();
        }
    
        public string StoreID { get; set; }
        public string SName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<tblExportReceipt> tblExportReceipts { get; set; }
    }
}
